### ISSUE TITLE
Add 'dogapi', '>= 1.15.0' in dependency

### ISSUE THREAD

**Issue by takus** [winebarrel/fluent-plugin-dd#2]
Hi,
I use this plugin, and sometime its thread hangs. As I discussed in https://github.com/DataDog/dogapi-rb/issues/66, it seems that https://github.com/DataDog/dogapi-rb/pull/55 is related to this issue. Could you consider to add `'dogapi', '>= 1.15.0'` in dependency?

**Comment by winebarrel** [comment]
Thank you for the issue :smiley: 
I'll add the `'dogapi', '>= 1.15.0'`.

**Comment by winebarrel** [comment]
v0.1.7 has been released.
Please try it out :smiley:

**Comment by takus** [comment]
Thank you very much :+1:
